### ISSUE TITLE
No Peer Certificate Error

### ISSUE THREAD

**Issue by MarkBorazio** [doorbell/android-sdk#23] opened 2021-07-04 17:59 UTC
When I present the Dialog, and also when I try to send the feedback, a "No Peer Certificate" toast appears.

I am seeing this occur on Pixel 2 emulators that are running API 21 and 22.
I do not have this issue on Pixel 2 emulators running API 28 and 29. I also do not have the issue on my own device (API 29).
I have not tested on other emulators at different API levels.

I can confirm that the dates on the emulators are correct, so at this point I have no idea what the cause of the issue is.

**Comment by manavo** [comment] 2021-07-04 18:24
Thanks for the heads up @MarkBorazio, and sorry for the trouble with this!

I'm assuming there might be a compatibility issue with older versions of Android and Let's Encrypt (which has issued the SSL certificate on the server).

I'll look into this, and it might be that Doorbell needs to drop support for the older SDKs!

**Comment by manavo** [comment] 2021-07-05 10:11
Hey @MarkBorazio, based on this: https://dev.ssllabs.com/ssltest/analyze.html?d=doorbell.io&s=192.241.183.155&hideResults=on&latest it looks like it should all work all the way back to Android 4.4.2 (which seems to be API versions 19-20). But I think the setup of the HTTP request might need some adjusting in order to better handle the different TLS versions. I'll keep digging into this!

Thanks,
Phil

**Comment by manavo** [comment] 2021-07-05 13:58
@MarkBorazio version 0.4.5 is tagged and on the way to being released. That fixes this problem.

The issue was using the old Apache HTTP client things, I've just updated it all to use the recommended HttpsURLConnection and the issue is resolved even in the older API versions (21-22).

**Comment by manavo** [comment] 2021-07-05 14:03
Version 0.4.5 is now available so I'm closing this. If the problem persists, let me know @MarkBorazio!

**Closed as completed by manavo** 2021-07-05 14:03 UTC

**Comment by MarkBorazio** [comment] 2021-07-10 15:18
Thanks @manavo for the extremely quick fix.
I just tested it now and it was all working.

**Comment by manavo** [comment] 2021-07-12 12:11
Thanks for confirming @MarkBorazio!
